Use RedisVL
RedisVentures/redis-arXiv-search pull request #19
Opened 2023-10-11 21:12 UTC by tylerhutcherson

Initial implementation that ports all functionality to use redisvl instead of base redis-py.

TODO still:
- [ ] figure out why sentence transformers `model.encode()` keeps seg faulting
- [ ] use redisvl vectorizers
- [ ] update docker image on GHCR and project README

2023-10-16 03:59 UTC, Spartee requested changes
First review, looks great. Crazy how much was able to be taken out. Few minor comments and design questions, but spending more time on RVL reviews. Will do more in depth after that.

2023-10-16 03:59 UTC, Spartee commented on backend/arxiv/api/routes.py
> +import typing as t
When we make this change, I'd love to just start using the types themselves. I'm not a fan of the ``t.`` methodology. 

Also, lots of untyped variables in here. also some that are ``list`` instead of ``List`` which can cause issues.

2023-10-16 03:59 UTC, Spartee commented on backend/arxiv/api/routes.py
> +from arxiv import config
I realize it was probably a pain to switch, but there is an ``arxiv`` python package and that may cause some confusion and/or issues if we ever use it.

``arxivguru``? ``axrivsearch``? somthing like that?

2023-10-16 03:59 UTC, Spartee commented on backend/arxiv/api/routes.py
> +redis_client = redis.from_url(config.REDIS_URL)
function with try/except?

2023-10-16 03:59 UTC, Spartee commented on backend/arxiv/api/routes.py
> +paper_vector_field_name = "vector"
needed?

2023-10-16 03:59 UTC, Spartee commented on backend/arxiv/api/routes.py
> +        await index._redis_conn.hget(paper_key, paper_vector_field_name),
``index.client`` should work here.

2023-10-16 03:59 UTC, Spartee commented on backend/arxiv/api/routes.py
> +async def find_papers_by_text(similarity_request: UserTextSimilarityRequest):
I don't think this is used?

2023-10-16 03:59 UTC, Spartee commented on backend/arxiv/load.py
> +    def preprocess_paper(paper: dict) -> dict:
types again in this file. ex. ``Dict`` instead of ``dict``

2023-10-16 03:59 UTC, Spartee commented on backend/arxiv/load.py
> +        if await index.exists():
wow this looks better...

2023-10-16 16:29 UTC, tylerhutcherson commented on backend/arxiv/api/routes.py
> +from arxiv import config
good catch! fixing

2023-10-16 16:30 UTC, tylerhutcherson commented on backend/arxiv/api/routes.py
> +redis_client = redis.from_url(config.REDIS_URL)
actually don't need this anymore -- removing

2023-10-16 16:33 UTC, tylerhutcherson commented on backend/arxiv/api/routes.py
> +paper_vector_field_name = "vector"
yeah, for now. I think we need to eventually enable access to the index's underlying schema object itself. it's abstracted and obfuscated right now

2023-10-16 16:33 UTC, tylerhutcherson commented on backend/arxiv/api/routes.py
> +        await index._redis_conn.hget(paper_key, paper_vector_field_name),
yep good catch

2023-10-16 16:33 UTC, tylerhutcherson commented on backend/arxiv/api/routes.py
> +async def find_papers_by_text(similarity_request: UserTextSimilarityRequest):
it is, this is the paper search bar where you type in natural language

2023-10-16 16:35 UTC, tylerhutcherson commented on backend/arxiv/api/routes.py
> +import typing as t
fixed!

2023-10-17 00:36 UTC, Spartee approved these changes
Approving, but there are some comments to look at. Overall this is a great change.

one thing that I think we can do is make the routes a bit more focused on RVL usage. like use ``VectorQuery`` directly instead of another function.

Nice work!

2023-10-17 00:36 UTC, Spartee commented on README.md
> +    <a href="https://github.com/RedisVentures/redis-arXiv-search"><img src="https://github.com/RedisVentures/redis-arXiv-search/blob/main/backend/arxiv/data/redis-logo.png?raw=true" width="30%"><img>
is this the right path?

2023-10-17 00:36 UTC, Spartee commented on backend/arxivsearch/api/routes.py
> +def create_vector_query(
is this function really needed?

2023-10-17 12:49 UTC, tylerhutcherson commented on backend/arxivsearch/api/routes.py
> +def create_vector_query(
reverted!

2023-10-17 12:51 UTC, merged